# Generated by Django 6.0.2 on 2026-02-21 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='corrects',
            field=models.ForeignKey(blank=True, help_text='If this is a correction entry, reference the original entry here.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='corrections', to='journal.journalentry', verbose_name='Corrects Entry'),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='transaction_type',
            field=models.CharField(choices=[('capital_contribution', 'Capital Contribution'), ('shareholder_withdrawal', 'Shareholder Withdrawal'), ('vendor_bill', 'Vendor Bill'), ('vendor_advance', 'Vendor Advance Payment'), ('vendor_payment', 'Vendor Payment Against Bill'), ('vendor_advance_settlement', 'Vendor Advance Settlement'), ('vendor_direct_payment', 'Vendor Direct Payment'), ('vendor_refund', 'Vendor Refund'), ('cash_expense', 'Cash Expense'), ('cashbox_transfer', 'Cashbox Transfer'), ('bank_deposit', 'Bank Deposit / Cash Withdrawal'), ('project_income', 'Project Income'), ('asset_purchase', 'Asset Purchase'), ('pay_salary', 'Pay Salary'), ('inventory_purchase', 'Inventory Purchase'), ('inventory_consumption', 'Inventory Consumption'), ('inventory_adjustment', 'Inventory Adjustment'), ('partner_inventory_contribution', 'Partner Inventory Contribution'), ('correction', 'Correction Entry'), ('manual', 'Manual Journal Entry')], default='manual', max_length=50, verbose_name='Transaction Type'),
        ),
    ]
