# Generated by Django 6.0.2 on 2026-02-26 07:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_name_from_user(apps, schema_editor):
    """Set name from the linked user's full name / username for existing rows."""
    ProjectPartner = apps.get_model("partners", "ProjectPartner")
    for pp in ProjectPartner.objects.select_related("user").filter(user__isnull=False):
        pp.name = pp.user.get_full_name() or pp.user.username
        pp.save(update_fields=["name"])


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0002_remove_partner_model'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='projectpartner',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='projectpartner',
            name='name',
            field=models.CharField(default='', max_length=200, verbose_name='Name'),
            preserve_default=False,
        ),
        migrations.RunPython(backfill_name_from_user, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='projectpartner',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_participations', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
