# Generated by Django 6.0.2 on 2026-02-19 07:53

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coa', '0001_initial'),
        ('core', '0001_initial'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('transaction_type', models.CharField(choices=[('capital_contribution', 'Capital Contribution'), ('shareholder_withdrawal', 'Shareholder Withdrawal'), ('vendor_bill', 'Vendor Bill'), ('vendor_advance', 'Vendor Advance Payment'), ('vendor_payment', 'Vendor Payment Against Bill'), ('cash_expense', 'Cash Expense'), ('cashbox_transfer', 'Cashbox Transfer'), ('bank_deposit', 'Bank Deposit / Cash Withdrawal'), ('project_income', 'Project Income'), ('asset_purchase', 'Asset Purchase'), ('pay_salary', 'Pay Salary'), ('manual', 'Manual Journal Entry')], default='manual', max_length=50, verbose_name='Transaction Type')),
                ('reference', models.CharField(blank=True, max_length=100, verbose_name='Reference')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_entries', to='projects.project', verbose_name='Project')),
            ],
            options={
                'verbose_name': 'Journal Entry',
                'verbose_name_plural': 'Journal Entries',
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='JournalLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debit', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18, verbose_name='Debit')),
                ('credit', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18, verbose_name='Credit')),
                ('exchange_rate', models.DecimalField(decimal_places=6, default=Decimal('1'), max_digits=18, verbose_name='Exchange Rate')),
                ('debit_tc', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18, verbose_name='Debit (TC)')),
                ('credit_tc', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18, verbose_name='Credit (TC)')),
                ('description', models.CharField(blank=True, max_length=300, verbose_name='Description')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='coa.account', verbose_name='Account')),
                ('journal_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='journal.journalentry', verbose_name='Journal Entry')),
                ('transaction_currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.currency', verbose_name='Currency')),
            ],
            options={
                'verbose_name': 'Journal Line',
                'verbose_name_plural': 'Journal Lines',
            },
        ),
    ]
