# Generated by Django 6.0.2 on 2026-02-19 07:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coa', '0001_initial'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Phone')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='System User')),
            ],
            options={
                'verbose_name': 'Partner',
                'verbose_name_plural': 'Partners',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProjectPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ownership_percent', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Ownership %')),
                ('capital_commitment', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Capital Commitment')),
                ('joined_at', models.DateField(verbose_name='Joined At')),
                ('exited_at', models.DateField(blank=True, null=True, verbose_name='Exited At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('capital_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='partner_capital_accounts', to='coa.account', verbose_name='Capital Account')),
                ('current_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='partner_current_accounts', to='coa.account', verbose_name='Current Account')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='project_participations', to='partners.partner', verbose_name='Partner')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_partners', to='projects.project', verbose_name='Project')),
            ],
            options={
                'verbose_name': 'Project Partner',
                'verbose_name_plural': 'Project Partners',
                'unique_together': {('project', 'partner')},
            },
        ),
    ]
