# Generated by Django 6.0.2 on 2026-02-21 12:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coa', '0001_initial'),
        ('journal', '0002_journalentry_corrects_and_more'),
        ('partners', '0001_initial'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Item Name')),
                ('unit', models.CharField(help_text='e.g. kg, bag, ton, liter, box', max_length=50, verbose_name='Unit')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expense_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_expense_accounts', to='coa.account', verbose_name='Expense Account')),
                ('inventory_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_accounts', to='coa.account', verbose_name='Inventory Account')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='projects.project', verbose_name='Project')),
            ],
            options={
                'verbose_name': 'Inventory Item',
                'verbose_name_plural': 'Inventory Items',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='InventoryMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('purchase', 'Purchase'), ('consumption', 'Consumption'), ('adjustment', 'Adjustment'), ('contribution', 'Partner Contribution')], max_length=20, verbose_name='Movement Type')),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=18, verbose_name='Quantity')),
                ('unit_cost', models.DecimalField(decimal_places=6, max_digits=18, verbose_name='Unit Cost')),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Total Cost')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='inventory.inventoryitem', verbose_name='Item')),
                ('journal_entry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_movements', to='journal.journalentry', verbose_name='Journal Entry')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_movements', to='projects.project', verbose_name='Project')),
                ('project_partner', models.ForeignKey(blank=True, help_text='Required only for partner contribution', null=True, on_delete=django.db.models.deletion.PROTECT, to='partners.projectpartner', verbose_name='Project Partner')),
            ],
            options={
                'verbose_name': 'Inventory Movement',
                'verbose_name_plural': 'Inventory Movements',
                'ordering': ['-created_at'],
            },
        ),
    ]
