# Generated by Django 6.0.2 on 2026-02-22 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
    ]
