# Generated by Django 6.0.2 on 2026-02-19 07:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coa', '0001_initial'),
        ('core', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cashbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='coa.account', verbose_name='Account')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.currency', verbose_name='Currency')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cashboxes', to='projects.project', verbose_name='Project')),
            ],
            options={
                'verbose_name': 'Cashbox',
                'verbose_name_plural': 'Cashboxes',
            },
        ),
    ]
