# Generated by Django 6.0.2 on 2026-02-19 07:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coa', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Phone')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('advance_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vendor_advance_accounts', to='coa.account', verbose_name='Advance Account')),
                ('payable_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vendor_payable_accounts', to='coa.account', verbose_name='Payable Account')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendors', to='projects.project', verbose_name='Project')),
            ],
            options={
                'verbose_name': 'Vendor',
                'verbose_name_plural': 'Vendors',
                'ordering': ['name'],
            },
        ),
    ]
