# Generated by Django 6.0.2 on 2026-02-27 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_remove_role_add_projectmember'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-created_at'], 'permissions': [('manage_members', 'Can manage project members'), ('add_financial_data', 'Can add / edit financial data')], 'verbose_name': 'Project', 'verbose_name_plural': 'Projects'},
        ),
        migrations.AlterField(
            model_name='projectmember',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('accountant', 'Accountant'), ('viewer', 'Viewer')], default='viewer', max_length=20, verbose_name='Role'),
        ),
    ]
