# Generated by Django 6.0.2 on 2026-02-19 07:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coa', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('salary_type', models.CharField(choices=[('monthly', 'Monthly'), ('daily', 'Daily')], max_length=20, verbose_name='Salary Type')),
                ('salary_amount', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Salary Amount')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('expense_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employee_expense_accounts', to='coa.account', verbose_name='Expense Account')),
                ('payable_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employee_payable_accounts', to='coa.account', verbose_name='Payable Account')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='projects.project', verbose_name='Project')),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
                'ordering': ['name'],
            },
        ),
    ]
